@server=http://localhost:4004
@username=alice
@password=


### Category
# @name Category_GET
GET {{server}}/odata/v4/catalog/Category
Authorization: Basic {{username}}:{{password}}


### Category
# @name Category_POST
POST {{server}}/odata/v4/catalog/Category
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  # "ID": "7486368a-a9cf-4d3c-b9a4-5152928f2bbe",
  "CategoryName": "CategoryName-748636",
  "Description": "Description-748636"
}


### Category
# @name Category_PATCH
PATCH {{server}}/odata/v4/catalog/Category/7486368a-a9cf-4d3c-b9a4-5152928f2bbe
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "7486368a-a9cf-4d3c-b9a4-5152928f2bbe",
  "CategoryName": "CategoryName-748636",
  "Description": "Description-748636"
}


### Category
# @name Category_DELETE
DELETE {{server}}/odata/v4/catalog/Category/7486368a-a9cf-4d3c-b9a4-5152928f2bbe
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}
