@server=http://localhost:4004
@username=alice
@password=


### Author
# @name Author_GET
GET {{server}}/odata/v4/catalog/Author
Authorization: Basic {{username}}:{{password}}


### Author
# @name Author_POST
POST {{server}}/odata/v4/catalog/Book
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "name":"harry brook",
  "rating" :"low"
}


### Author
# @name Author_PATCH
PATCH {{server}}/odata/v4/catalog/Author/47917215-4fe0-4aec-a543-36a74d2caf8b
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "47917215-4fe0-4aec-a543-36a74d2caf8b",
  "name": "name-4791721",
  "address": "address-4791721",
  "books": [
    {
      "ID": "5950063d-d9cb-4c01-94d7-bd3d65506e08",
      "name": "name-5950063",
      "createdAt": "2010-06-21T00:00:00.000Z",
      "createdBy": "createdBy.3jj3j@example.com",
      "modifiedAt": "2019-03-18T00:00:00.000Z",
      "modifiedBy": "modifiedBy.3jj3j@example.net"
    },
    {
      "ID": "59500647-6a6a-4a0d-b488-be641878de95",
      "name": "name-5950064",
      "createdAt": "2005-06-15T00:00:00.000Z",
      "createdBy": "createdBy.3jj3k@example.com",
      "modifiedAt": "2004-10-09T00:00:00.000Z",
      "modifiedBy": "modifiedBy.3jj3k@example.com"
    }
  ],
  "createdAt": "2000-04-16T00:00:00.000Z",
  "createdBy": "createdBy.2upbd@example.net",
  "modifiedAt": "2006-05-13T00:00:00.000Z",
  "modifiedBy": "modifiedBy.2upbd@example.com"
}


### Author
# @name Author_DELETE
DELETE {{server}}/odata/v4/catalog/Author/47917215-4fe0-4aec-a543-36a74d2caf8b
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}


### Book
# @name Book_GET
GET {{server}}/odata/v4/catalog/Book
Authorization: Basic {{username}}:{{password}}


### Book
# @name Book_POST
POST {{server}}/odata/v4/catalog/Book
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "5950063d-d9cb-4c01-94d7-bd3d65506e08",
  "name": "name-5950063",
  "createdAt": "2010-06-21T00:00:00.000Z",
  "createdBy": "createdBy.3jj3j@example.com",
  "modifiedAt": "2019-03-18T00:00:00.000Z",
  "modifiedBy": "modifiedBy.3jj3j@example.net"
}


### Book
# @name Book_PATCH
PATCH {{server}}/odata/v4/catalog/Book/5950063d-d9cb-4c01-94d7-bd3d65506e08
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "5950063d-d9cb-4c01-94d7-bd3d65506e08",
  "name": "name-5950063",
  "createdAt": "2010-06-21T00:00:00.000Z",
  "createdBy": "createdBy.3jj3j@example.com",
  "modifiedAt": "2019-03-18T00:00:00.000Z",
  "modifiedBy": "modifiedBy.3jj3j@example.net"
}


### Book
# @name Book_DELETE
DELETE {{server}}/odata/v4/catalog/Book/5950063d-d9cb-4c01-94d7-bd3d65506e08
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}
