@server=http://localhost:4004
@username=alice
@password=


### Categories
# @name Categories_GET
GET {{server}}/odata/v4/catalog/Categories?$expand=products
Authorization: Basic {{username}}:{{password}}


### Categories
# @name Categories_POST
POST {{server}}/odata/v4/catalog/Categories
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "1776889e-ddd6-4645-94b2-9aa4a9d23ba3",
  "CategoryName": "CategoryName-1776889",
  "Description": "Description-1776889",
  "createdAt": "2020-07-24T00:00:00.000Z",
  "createdBy": "createdBy.12321@example.org",
  "modifiedAt": "2012-07-25T00:00:00.000Z",
  "modifiedBy": "modifiedBy.12321@example.net"
}


### Categories
# @name Categories_PATCH
PATCH {{server}}/odata/v4/catalog/Categories/1776889e-ddd6-4645-94b2-9aa4a9d23ba3
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "1776889e-ddd6-4645-94b2-9aa4a9d23ba3",
  "CategoryName": "CategoryName-1776889",
  "Description": "Description-1776889",
  "createdAt": "2020-07-24T00:00:00.000Z",
  "createdBy": "createdBy.12321@example.org",
  "modifiedAt": "2012-07-25T00:00:00.000Z",
  "modifiedBy": "modifiedBy.12321@example.net"
}


### Categories
# @name Categories_DELETE
DELETE {{server}}/odata/v4/catalog/Categories/1776889e-ddd6-4645-94b2-9aa4a9d23ba3
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}
